CREATE TABLE IF NOT EXISTS actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE,
    UNIQUE (user_id, event_id, action_type)
);

CREATE TABLE IF NOT EXISTS similarities (
    event_a_id BIGINT,
    event_b_id BIGINT,
    rating FLOAT,
    timestamp TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (event_a_id, event_b_id)
);