spring:
  config:
    activate:
      on-profile: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:main
    username: main
    password: main
  h2:
    console.enabled: true
  jpa:
    show-sql: TRUE
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

hibernate:
  show_sql: TRUE

logging:
    ru:
      practicum: TRACE