services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  request-db:
    image: postgres:16.1
    container_name: request-service-db
    ports:
      - "7432:5432"
    environment:
      - POSTGRES_DB=request_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  event-db:
    image: postgres:16.1
    container_name: event-service-db
    ports:
      - "7433:5432"
    environment:
      - POSTGRES_DB=event_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  user-db:
    image: postgres:16.1
    container_name: user-service-db
    ports:
      - "7434:5432"
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  comment-db:
    image: postgres:16.1
    container_name: comment-service-db
    ports:
      - "7435:5432"
    environment:
      - POSTGRES_DB=comment_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                  'kafka-topics --create --topic stats.events-similarity.v1 \
                               --partitions 1 --replication-factor 1 --if-not-exists \
                               --bootstrap-server kafka:29092 && \
                  kafka-topics --create --topic stats.user-actions.v1 \
                               --partitions 1 --replication-factor 1 --if-not-exists \
                               --bootstrap-server kafka:29092'"
    init: true

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8088:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true